name: ansel
version: "0.0.0"
adopt-info: ansel
grade: stable
confinement: strict
base: core24
compression: lzo

donation: "https://liberapay.com/aurelienpierre"
source-code: "https://github.com/aurelienpierreeng/ansel"
website: "https://ansel.photos"

apps:
  ansel:
    command: usr/bin/ansel --datadir $SNAP/usr/share/ansel --moduledir $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ansel --configdir $SNAP_USER_DATA --localedir $SNAP/usr/share/locale
    environment:
      GTK_USE_PORTAL: 0
    extensions: [gnome]
    plugs:
      - opengl
      - home
      - removable-media
      - password-manager-service
      - network
      - network-bind
    common-id: photos.ansel.app
  cli:
    command: usr/bin/ansel-cli --datadir $SNAP/usr/share/ansel --moduledir $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ansel --configdir $SNAP_USER_DATA --localedir $SNAP/usr/share/locale
    extensions: [gnome]
    plugs:
      - opengl
      - home
      - removable-media
      - password-manager-service
      - network
      - network-bind
      # https://forum.snapcraft.io/t/help-gdbus-error-this-call-is-not-available-inside-the-sandbox/29969/5
      - network-status

  lensfun-update-data:
    command: usr/bin/lensfun-update-data
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    plugs:
      - network

slots:
  session-dbus-interface:
    interface: dbus
    name: org.darktable.service
    bus: session

layout:
  /usr/include/clc:
    symlink: $SNAP/usr/include/clc
  /usr/lib/clc:
    symlink: $SNAP/usr/lib/clc
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gallium-pipe:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gallium-pipe
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl

build-packages:
  - gcc-12
  - g++-12

parts:
  opencl:
    plugin: nil
    stage-packages:
      - mesa-opencl-icd
      - ocl-icd-libopencl1
      - on amd64:
        - intel-opencl-icd

  ansel:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      # Place the data alongside that coming from stage-packages (e.g. the lensfun database)
      - -DCMAKE_INSTALL_PREFIX=/usr
      # Support Lua scripts by way of internal Lua implementation
      - -DDONT_USE_INTERNAL_LUA=OFF
      # Don't overly optimize for build CPU-- stay generic
      - -DBINARY_PACKAGE_BUILD=ON
      - -DCMAKE_FIND_ROOT_PATH="$SNAPCRAFT_STAGE;/snap/gnome-42-2204-sdk/current"
      - -DCMAKE_VERBOSE_MAKEFILE=ON
      - -DUSE_LIGHTROOM=ON
      - -DUSE_COLORD=ON
    stage-packages:
      - libasn1-8-heimdal
      - libavif16
      - libcurl3-gnutls
      - libexiv2-27
      - libgraphicsmagick-q16-3
      - libgssapi3-heimdal
      - libhcrypto5t64-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libimage-exiftool-perl
      - libkrb5-26-heimdal
      - libgphoto2-6
      - liblensfun-bin
      - liblensfun-data-v1
      - liblensfun1
      - libnghttp2-14
      - libpugixml1v5
      - libroken19t64-heimdal
      - librtmp1
      - libsasl2-2
      - libssh-4
      - libwind0-heimdal
    build-packages:
      - intltool
      - libavif-dev
      - libexiv2-dev
      - libgraphicsmagick1-dev
      - liblensfun-dev
      - libgphoto2-dev
      - libpugixml-dev
      - libsdl2-dev
      - libsm-dev
      - libxml2-utils
      - libxrandr-dev
      - ninja-build
      - patch
      - pkg-config
      - xsltproc
      # -- Missing jsonschema, problems in noiseprofiles.json might go unnoticed
      # -- GMIC not found

      # Disabled capabilities for now due to interfaces:
      #
      # Need to test with cups-control interface
      # - libcups2-dev

    build-environment:
      - LDFLAGS: "-L${CRAFT_STAGE}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR} $(pkg-config --libs libheif sdl2 harfbuzz gtk+-3.0 OpenEXR)"
      # [-Werror=shadow]
      # :: src/src/gui/guides.c:534:63: error: declaration of ‘free’ shadows a global declaration
      - CFLAGS: "-O3 $(pkg-config --cflags libheif sdl2 harfbuzz OpenEXR) -Wno-error=type-limits -Wno-error=shadow -Wno-error=unused-value"
      # [-Werror=shadow]
      # :: usr/include/OpenEXR/ImfRational.h:48:26: error: declaration of ‘d’ shadows a member of ‘Imf_3_1::Rational’
      - CXXFLAGS: "-O3 $(pkg-config --cflags libheif sdl2 harfbuzz OpenEXR) -Wno-error=register -Wno-error=shadow"
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags)
      patch -p0 < "${SNAPCRAFT_PROJECT_DIR}/snap/local/patches/darktable-math_h.patch"
      patch -p0 < "${SNAPCRAFT_PROJECT_DIR}/snap/local/patches/darktable-lens_cc.patch"
    override-build: |
      snapcraftctl build
      PYTHONPATH=$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages $SNAPCRAFT_PART_INSTALL/usr/bin/lensfun-update-data || echo No updates
      if [ -d /var/lib/lensfun-updates/version_1/]; then
        cp /var/lib/lensfun-updates/version_1/* $SNAPCRAFT_PART_INSTALL/usr/share/lensfun/version_1/
      fi
    parse-info:
      - usr/share/metainfo/photos.ansel.app.appdata.xml
    stage:
      - -usr/share/man
      - -usr/lib/llvm-15
      - -usr/lib/clang
    after:
      - colord
      - openexr
      - osmgpsmap

  colord:
    source: https://www.freedesktop.org/software/colord/releases/colord-gtk-0.3.0.tar.xz
    source-checksum: sha256/b9466656d66d9a6ffbc2dd04fa91c8f6af516bf9efaacb69744eec0f56f3c1d0
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dman=false
      - -Ddocs=false
    build-packages:
      - meson
      - libcolord-dev

  openexr:
    source: https://github.com/AcademySoftwareFoundation/openexr/archive/refs/tags/v3.2.4.tar.gz
    source-checksum: sha256/81e6518f2c4656fdeaf18a018f135e96a96e7f66dbe1c1f05860dd94772176cc
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DDOCS=OFF
      - -DOPENEXR_INSTALL_EXAMPLES=OFF
      - -DOPENEXR_BUILD_TOOLS=OFF
      - -DOPENEXR_INSTALL_TOOLS=OFF
    build-packages:
      - libimath-dev
    build-environment:
      - CFLAGS: "-O3"
    prime:
      - -usr/include

  osmgpsmap:
    source: https://github.com/nzjrs/osm-gps-map/releases/download/1.2.0/osm-gps-map-1.2.0.tar.gz
    source-checksum: sha256/ddec11449f37b5dffb4bca134d024623897c6140af1f9981a8acc512dbf6a7a5
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-introspection=no
    build-packages:
      - libcurl4-gnutls-dev
      - libssl-dev
      - libsoup2.4-dev
    build-environment:
      - CFLAGS: "-O3"
      - CXXFLAGS: "-O3"
    prime:
      - -usr/include
